# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tim Jansson
email: tim@timtux.net
description: >
  Min utvecklingsdagbok där jag publicerar lösningar på problem som uppstår i
  min vardag. Många poster kommer vara slarvigt skrivna men alla gånger jag försökt
  mig på detta tidigare har det slutat i att jag strävat efter så mycket perfektion
  att jag inte fått något publicerat.
baseurl: "/timjansson.se" # the subpath of your site, e.g. /blog
url: "http://timtux.github.io/" # the base hostname & protocol for your site
twitter_username: timtux
github_username:  timtux

# Build settings
markdown: kramdown
